### PR TITLE
Snowflake parser improvements - quote handling

### PR DESCRIPTION
**Pull request by arvislacis**
Improvements for https://github.com/skripteria/wn-snowflake-plugin/issues/18
This should be tested a bit before merging although worked fine for my edge cases and I don't see very problematic parts in changes.

Improvements made in this pull request:
- Simplified the main regex so it only captures only spaces in `{{ sf_key | sf() }}`, not all characters (`.*`) - this avoids greedy capturing and solves problem with brackets (if `()` were used in description parameter);
- Also additional quote usage problem in parameter values is now solved - this is done by treating `$param_string` as CSV string so PHP native function automatically processes commas and quotes.

If this pull request is ok then we can probably close https://github.com/skripteria/wn-snowflake-plugin/issues/18

There is one super-edge cases which this doesn't solve - `{{ test_key|sf('text', "test", 'Test description...') }}` - when mixed quotes are used for each parameter but it would be very problematic to solve cases like this.

### CODE REVIEW

**Review by skripteria — COMMENTED** [review]
Interesting CSV trick that you are introducing here!
On the first glance it looks ok, but as you say I will run some tests on it before merging.

**Comment by skripteria** [comment]
Unfortunately I hit an issue when I did the first tests:

This method breaks somehow when I want to combine the sf filter with the resize filter, example usage:
```
<img src="{{sf_image | resize(400,400,{mode:'crop'})  | sf('image','','desc') }}" alt="{{sf_image__alt}}">
```

**Comment by arvislacis** [comment]
I see...

`preg_match_all('|\{{2}\s*(\w+)\s*\|\s*sf\((.*)\)\s*}{2}|U', $content, $matches);` should be changed back to `preg_match_all('|\{{2}.*\s*(\w+)\s*\|.*sf\((.*)\).*\}{2}|U', $content, $matches);` then it should be fine again (although that would revert back bracket issue but that's not so critical).

**Comment by arvislacis** [comment]
In other words, need to apply this commit - https://github.com/arvislacis/wn-snowflake-plugin/commit/630254b34c4233622c8a35be2cf645a414d3e061 so other Twig filter combination with Snowflake filter would be possible again.

**Comment by arvislacis** [comment]
Although, when I think about it a bit more:

```twig
<img src="{{sf_image | resize(400,400,{mode:'crop'})  | sf('image','','desc') }}" alt="{{sf_image__alt}}">
```

^ This should not be valid option, `sf()` should always follow only after the Snowflake key name..., otherwise if you combine it with other Twig filters then parser could save also Twig filter ar a Snowflake key name, for example, if using filters like  `capitalize` etc.

**Comment by skripteria** [comment]
Thanks!
I will apply it and test again, however it may take a little while since I am busy this afternoon ;)

**Comment by arvislacis** [comment]
Ok, no worries. I also made new pull request (https://github.com/skripteria/wn-snowflake-plugin/pull/22) to your testing branch with this change so you can merge it in directly.

**Pull request merged**
